# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('fbProfileLink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDateTime', models.DateTimeField()),
                ('toDateTime', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-fromDateTime'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isApproved', models.BooleanField(default=False)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event')),
            ],
        ),
        migrations.CreateModel(
            name='SIG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fromTime', models.TimeField()),
                ('toTime', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-date', 'fromTime'],
            },
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publishedOn'], 'verbose_name_plural': 'News'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='postedBy',
        ),
        migrations.DeleteModel(
            name='Coordinator',
        ),
        migrations.AddField(
            model_name='member',
            name='sig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SIG'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='councilmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Member'),
        ),
        migrations.AddField(
            model_name='news',
            name='publishedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Member'),
            preserve_default=False,
        ),
    ]
