# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170806_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Event'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.SIG'),
        ),
    ]
