# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170806_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='event',
        ),
        migrations.RemoveField(
            model_name='member',
            name='sig',
        ),
        migrations.AddField(
            model_name='event',
            name='coordinators',
            field=models.ManyToManyField(to='api.Member'),
        ),
        migrations.AddField(
            model_name='sig',
            name='coordinators',
            field=models.ManyToManyField(to='api.Member'),
        ),
    ]
